site_name: High Throughput Computing Facility @ CGSSB
theme: 
  name: material
  logo: shield-light.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: wustl_gray
    
extra_css:
  - stylesheets/extra.css

extra:
  font:
    text: 'Roboto'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - def_list
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - macros
  - search
  
extra:
  lts:
    price: 6.73

nav:
- The HTCF: 'index.md'
- Doing Work:
    - Getting Started: 'getstarted.md'
    - Running Jobs: runningjobs.md
    - The Queue: using/queue.md
    - Using the HTCF: 'using/index.md'
    - Batch Jobs: 'using/batch.md'
    - Interactive Jobs: 'using/interactive.md'
    - Job Accounting: 'using/accounting.md'
      #- queue.md
      #- runningjobs.md
- Policies: 'policies.md'
- Storage: 
    - Overview: 'storage/index.md'
    - HTS: 'storage/hts.md'
    - REF: 'storage/ref.md'
    - LTS: 'storage/lts.md'
    - LTOS: 'storage/ltos.md'
    - Beta: 'storage/new_index.md'
- Software: 
  - Overview: software.md
  - Beta: software_new.md
