site_name: HTCF
theme: 'material'
extra:
  font:
    text: 'Roboto'
pages:
- Home: 'index.md'
- About:
  - 'Policies': 'policies.md'
- Resources:
  - 'Genomes': 'genomes.md'
  - 'Getting Started': 'getstarted.md'
  - 'Running Jobs' : 'runningjobs.md'
  - 'SLURM': 'queue.md'
  - 'Software List': 'softwarelist.md'
  - 'Software Modules': 'software.md'
  - 'Storage': 'storage.md'
  - 'Support': 'support.md'
