site_name: HTCF
theme: 
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: preference
    
extra:
  font:
    text: 'Roboto'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - macros
  
nav:
- Getting Started: 'getstarted.md'
- Policies: 'policies.md'
- Storage: 'storage/index.md'
- Software: 'software.md'
- Support: 'support.md'
