site_name: HTCF
theme: 'material'
extra:
  font:
    text: 'Roboto'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - macros
  
nav:
- Home: 'index.md'
- About:
  - 'Policies': 'policies.md'
- Resources:
  - 'Genomes': 'genomes.md'
  - 'Getting Started': 'getstarted.md'
  - 'Running Jobs' : 'runningjobs.md'
  - 'SLURM': 'queue.md'
  - 'Software List': 'softwarelist.md'
  - 'Software Modules': 'software.md'
  - 'Storage': 'storage/index.md'
  - 'Support': 'support.md'
